version: '3.8'

services:
  # L&A Logistics Web Application
  lalogistics-app:
    build: .
    container_name: lalogistics-web
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - MONGODB_URI=mongodb://192.168.1.200:27017/lalogistics
      - SESSION_SECRET=${SESSION_SECRET:-your-random-secret-key-here}
      - PORT=3000
    volumes:
      - uploads-data:/app/public/uploads

volumes:
  uploads-data:
    driver: local
